### ISSUE TITLE
master報錯，找不到這個，用的4.25	ADD_STATIC_FUNCTION_EX("ProjectSavedDir", FString, ProjectSavedDir)

### ISSUE THREAD

**Issue by fengdays** [hxhb/debugable-unlua#3]
master報錯，找不到這個，用的4.25	ADD_STATIC_FUNCTION_EX("ProjectSavedDir", FString, ProjectSavedDir)

**Comment by BA3000** [comment]
4.26同报了这个错误

**Comment by BA3000** [comment]
![image](https://user-images.githubusercontent.com/35647825/118233167-2149b380-b4c4-11eb-8b95-44db586d9da7.png)

报错信息如上

`ProjectSavedDir`对应的函数应该是`Paths.cpp`中的`const FString& FPaths::ProjectSavedDir()`，这个错误是指没有找到对应的函数。

在4.24版本的引擎中原本的代码是：

``` c++
FString FPaths::ProjectSavedDir()
{
	static FString Result = UE4Paths_Private::GameSavedDir();
	return Result;
}
```

不知道为什么4.25及26变成了：

```C++
const FString& FPaths::ProjectSavedDir()
{
	FStaticData& StaticData = TLazySingleton<FStaticData>::Get();
	if (!StaticData.bGameSavedDirInitialized)
	{
		StaticData.GameSavedDir = UE4Paths_Private::GameSavedDir();
		StaticData.bGameSavedDirInitialized = true;
	}
	return StaticData.GameSavedDir;
}
```

所以会报错。

**Comment by BA3000** [comment]
已经搞清楚怎么回事了，解决方案就是将原本的

```c++
ADD_STATIC_FUNCTION_EX("ProjectSavedDir", FString, ProjectSavedDir)
```
改为：
```c++
ADD_STATIC_FUNCTION_EX("ProjectSavedDir", const FString&, ProjectSavedDir)
```
后面我会修改一下源码，merge回去，根据引擎版本判断来更换传入的参数

**Comment by BA3000** [comment]
其实应该可以关闭这个issue了。我自己测试的话在4.26环境下已经可以导入。导入后初步使用了下，没有遇到什么问题。自己查看了下4.25相关的代码，这个问题对应的代码4.25和4.26没有差别，所以应该是解决了。
