### ISSUE TITLE
更新LuaPanda到3.2

### ISSUE THREAD

**Issue by chentmin** [hxhb/debugable-unlua#8]
> 因为单个LuaPanda.lua在include时文件太长不可以直接包含，所以我写了个工具把LuaPanda.lua的内容转换为了LuaPanda.inl

请问能升一下级, 或者也开源一下转换的工具吗? 谢谢

**Comment by hxhb** [comment]
@chentmin 我写了一个[bin2hex](https://gist.github.com/hxhb/9019a284ae9b6cfa1436414e04145d59)的程序，使用这份代码编译之后，将.lua文件转换为字符数组替换即可。
